export const data = [
    {
        id: 1,
        logo: "NHM.png",
        logoH: '70px',
        logoW: '70px',
        name: "National Health Mission",
        img1: "Book cover.jpg",
        img2: "Print Ad 1.jpg",
        img3: "Print Ad 2.jpg",
        img4: "Print Ad.jpg",
        img5: "Standee.jpg"
    },
    {
        id: 2,
        logo: "apollo.png",
        logoH: '70pxpx',
        logoW: '65px',
        name: "Apollo",
        img1: "ApolloCalendar.jpg",
        img2: "ApolloDigital Screen.jpg",
        img3: "ApolloLeaflet.jpg",
        img4: "ApolloPoster.jpg",
        img5: "ApolloSocial media post.jpg"
    },
    {
        id: 3,
        logo: "ACCF.png",
        logoH: '70px',
        logoW: '100px',
        name: "Assam Cancer Care Foundation",
        img1: "ACCFInstallions.jpg",
        img2: "ACCFOutdoor creative.jpg",
        img3: "ACCFStandee.jpg",
        img4: "ACCFwall panels.jpg",
    },
    {
        id: 4,
        logo: "aids.png",
        logoH: '70px',
        logoW: '70px',
        name: "Assam State Aids Control Society",
        img1: "ASACSSocial media post (1).jpg",
        img2: "ASACSSocial media post (2).jpg",
        img3: "ASACSSocial media post (3).jpg",
        img4: "ASACSSocial media post (4).jpg",
    },
    {
        id: 5,
        logo: "AtalAmritSociety.png",
        logoH: '70px',
        logoW: '100px',
        name: "Atal Amrit Abhiyan Society, Assam",
        img1: "AtalAmritMobile Van.jpg",
        img2: "AtalAmritPrint Ad 1.jpg",
        img3: "AtalAmritPrint Ad 2.jpg",
        img4: "AtalAmritPrint Ad.jpg",
    },
    {
        id: 6,
        logo: "DOA.png",
        logoH: '60px',
        logoW: '190px',
        name: "Department of Agriculture, \n Government of Assam",
        img1: "DOABackdrop.jpg",
        img2: "DOASocial media 2.jpg",
        img3: "DOASocial post 1.jpg",
        img4: "DOASocial post.jpg"

    },
    {
        id: 7,
        logo: "ARIAS.png",
        logoH: '70px',
        logoW: '145px',
        name: "ARIAS Society",
        img1: "AriasHoarding.jpg",
        img2: "AriasLeaflet.jpg",
        img3: "AriasMobile LED  Van.jpg",
        img4: "AriasSocial Media Post.jpg",
        img5: "AriasStandee.JPG",
    },
    {
        id: 8,
        logo: "SwachchhBharat.png",
        logoH: '70px',
        logoW: '145px',
        name: "Swachh Bharat Mission Grameen, Assam",
        img1: "SwachhBharatCalendar.jpg",
        img2: "SwachhBharatFull page print ad.jpg",
        img3: "SwachhBharatHorading.jpg",
        img4: "SwachhBharatPoster.jpg",
        img5: "SwachhBharatSocial media post 1.JPG",
    },
    // {
    //     id: 9,
    //     logo: "DOTTW.png",
    //     logoH: '70px',
    //     logoW: '80px',
    //     name: "Directorate of Tree Tribes Welfare, Assam",
    // },
    {
        id: 9,
        logo: "APART Logo2.png",
        logoH: '70px',
        logoW: '70px',
        name: "APART",
        img1: "APARTHoarding.jpg",
        img2: "APARTLeaflet.jpg",
        img3: "APARTMobile Van.jpg",
        img4: "APARTSocial Media Post.jpg",
        img5: "APARTStandee.JPG",
    },
    {
        id: 10,
        logo: "BrahmaputraBoard.png",
        logoH: '70px',
        logoW: '60px',
        name: "Brahmaputra Board",
        img1: "Brahmaputra board logo.jpg",
        img2: "BrahmaputraBoardCofee Table book.jpg",
        img3: "BrahmaputraBoardPress meet.jpg",
        img4: "BrahmaputraBoardSocial media promotions.jpg",
    },
    {
        id: 11,
        logo: "DOH.jpeg",
        logoH: '70px',
        logoW: '95px',
        name: "Directorate of Horticulture & Food Processing",
        img1: "DeptHortiBanner 1.jpg",
        img2: "DeptHortiBanner.jpg",
        img3: "DeptHortiSocial post 1.jpg",
        img4: "DeptHortiSocial post 2.jpg",
    },
    // {
    //     id: 10,
    //     logo: "DOT.png",
    //     logoH: '70px',
    //     logoW: '230px',
    //     name: "Directorate of Tourism",
    // },
    // {
    //     id: 11,
    //     logo: "AssamTourismDev.png",
    //     logoH: '70px',
    //     logoW: '90px',
    //     name: "Assam Tourism Development Corporation",
    // },
    {
        id: 12,
        logo: "GMC.png",
        logoH: '70px',
        logoW: '70px',
        name: "Guwahati Municipal Corporation (GMC)",
        img1: "GMCHoarding.jpg",
        img2: "GMCPoster.jpg",
        img3: "GMCPrint Ad.jpg",
        img4: "GMCSingage.jpg",
        img5: "GMCStandee.JPG",
    },
    {
        id: 13,
        logo: "ASDMA.png",
        logoH: '70px',
        logoW: '80px',
        name: "Assam State Disaster Management Authority (ASDMA)",
        img1: "AsdmaFull Page Print Ad.jpg",
        img2: "AsdmaPrint Ad.jpg",
        img3: "AsdmaSocial media post 1.jpg",
        img4: "AsdmaSocial media post.jpg",
    },
    {
        id: 14,
        logo: "Purabi.png",
        logoH: '70px',
        logoW: '60px',
        name: "West Assam Milk Producers Co-operative Union (Purabi)",
        img1: "PurabiCalender Mockup.jpg",
        img2: "PurabiDiary Cover.jpg",
        img3: "PurabiHoarding.jpg",
        img4: "PurabiStandee.jpeg",
        img5: "PurabiStore branding.jpg",
    },
    {
        id: 15,
        logo: "JJM.png",
        logoH: '70px',
        logoW: '70px',
        name: "Jal Jeevan Mission Assam",
        img1: "JJMAPost 14 copy.jpg",
        img2: "JJMAPost 17 copy.jpg",
        img3: "JJMAPost 28 copy.jpg",
        img4: "JJMAStandee.jpeg",
        img5: "JJMASocial media post 2.jpg",
    },
    // {
    //     id: 15,
    //     logo: "Nedfi.png",
    //     logoH: '70px',
    //     logoW: '90px',
    //     name: "North Eastern Development Finance Corporation Ltd.",
    // },
    {
        id: 16,
        logo: "FSSAI.png",
        logoH: '70px',
        logoW: '100px',
        name: "Commissionerate of Food Safety, Govt. of Assam",
        img1: "FSSAIHalf Page Press Ad.jpg",
        img2: "FSSAILeaflet.jpg",
        img3: "FSSAISocial media post.jpg",
        img4: "FSSAIStandee.jpg",
        img5: "FSSAIWelcome Board.jpg",
    },
    // {
    //     id: 17,
    //     logo: "APFBC.png",
    //     logoH: '70px',
    //     logoW: '70px',
    //     name: "Assam Project on Forest & Biodiversity Conservation",
    // },
    {
        id: 18,
        logo: "MPM.png",
        logoH: '70px',
        logoW: '120px',
        name: "Madhya Pradesh Metro Rail Corporation Ltd.",
        img1: "MPMSocial media post 1  (1).jpg",
        img2: "MPMSocial media post 1  (2).jpg",
        img3: "MPMSocial media post 1  (3).jpg",
        img4: "MPMSocial media post 1  (4).jpg",
        img5: "MPMSocial media post 1  (5).jpg",
    },
    {
        id: 19,
        logo: "CCI.png",
        logoH: '70px',
        logoW: '90px',
        name: "Competition Commission of India",
        img1: "CCISocial media post 1.jpg",
        img2: "CCISocial media post 2.jpg",
        img3: "CCISocial media post 3.jpg",
        img4: "Social media post 4.jpg",
    },
    {
        id: 20,
        logo: "NRL.png",
        logoH: '70px',
        logoW: '70px',
        name: "Numaligarh Refinery Limited (NRL)",
        img1: "NRLHoarding 1.jpg",
        img2: "NRLHoarding 2.jpg",
        img3: "NRLHoarding 3.jpg",
        img4: "NRLHoarding 1.jpg",
    },
    // {
    //     id: 21,
    //     logo: "AUIIP.png",
    //     logoH: '70px',
    //     logoW: '80px',
    //     name: "Assam Urban Infrastructure Investment Program (AUIIP)",
    // },
    {
        id: 22,
        logo: "UPSIDA.png",
        logoH: '70px',
        logoW: '140px',
        name: "Uttar Pradesh State Industrial Development Authority (UPSIDA)",
        img1: "UPSIDASocial media post 1.jpg",
        img2: "UPSIDASocial media post 2.jpg",
        img3: "UPSIDASocial media post 3.jpg",
        img4: "UPSIDASocial media post 4.jpg",
    },
    {
        id: 23,
        logo: "JJM.png",
        logoH: '70px',
        logoW: '70px',
        name: "Jal Jeevan Mission Meghalaya",
        img1: "JJMMSocial media post 1.jpg",
        img2: "JJMMSocial media post 2.jpg",
        img3: "JJMMSocial media post 3.jpg",
        img4: "JJMMSocial media post.jpg",
    },
    // {
    //     id: 24,
    //     logo: "EkLakshya.png",
    //     logoH: '70px',
    //     logoW: '120px',
    //     name: "Regional Outreach Bureau, Rajasthan",
    // },
    {
        id: 25,
        logo: "SharpSight.png",
        logoH: '70px',
        logoW: '80px',
        name: "Sharp Sight",
        img1: "SharpsightPrint Ad 1.jpg",
        img2: "SharpsightPrint Ad 2.jpg",
        img3: "SharpsightSocial media post 1.jpg",
        img4: "SharpsightSocial media post 2.jpg",
    }
];