export const data = [
    {
        id: 1,
        logo: "NHM.png",
        logoH: '70px',
        logoW: '70px',
        labelMarginTop: '5px',
        name: "National Health Mission",
    },
    {
        id: 2,
        logo: "apollo.png",
        logoH: '70pxpx',
        logoW: '65px',
        labelMarginTop: '5px',
        name: "Apollo",
    },
    {
        id: 3,
        logo: "ACCF.png",
        logoH: '70px',
        logoW: '100px',
        name: "Assam Cancer Care Foundation",
    },
    {
        id: 4,
        logo: "aids.png",
        logoH: '70px',
        logoW: '70px',
        name: "Assam State Aids Control Society",
    },
    {
        id: 5,
        logo: "AtalAmritSociety.png",
        logoH: '70px',
        logoW: '100px',
        name: "Atal Amrit Abhiyan Society, Assam",
    },
    {
        id: 6,
        logo: "DOA.png",
        logoH: '70px',
        logoW: '230px',
        name: "Department of Agriculture, \n Government of Assam",
    },
    {
        id: 7,
        logo: "ARIAS.png",
        logoH: '70px',
        logoW: '145px',
        name: "ARIAS Society",
    },
    {
        id: 8,
        logo: "SwachchhBharat.png",
        logoH: '70px',
        logoW: '145px',
        name: "Swachh Bharat Mission Grameen, Assam",
    },
    {
        id: 9,
        logo: "DOTTW.png",
        logoH: '70px',
        logoW: '80px',
        name: "Directorate of Tree Tribes Welfare, Assam",
    },
    {
        id: 10,
        logo: "DOT.png",
        logoH: '70px',
        logoW: '230px',
        name: "Directorate of Tourism",
    },
    {
        id: 11,
        logo: "AssamTourismDev.png",
        logoH: '70px',
        logoW: '90px',
        name: "Assam Tourism Development Corporation",
    },
    {
        id: 12,
        logo: "GMC.png",
        logoH: '70px',
        logoW: '70px',
        name: "Guwahati Municipal Corporation (GMC)",
    },
    {
        id: 13,
        logo: "ASDMA.png",
        logoH: '70px',
        logoW: '80px',
        name: "Assam State Disaster Management Authority (ASDMA)",
    },
    {
        id: 14,
        logo: "Purabi.png",
        logoH: '70px',
        logoW: '60px',
        name: "West Assam Milk Producers Co-operative Union (Purabi)",
    },
    {
        id: 15,
        logo: "Nedfi.png",
        logoH: '70px',
        logoW: '90px',
        name: "North Eastern Development Finance Corporation Ltd.",
    },
    {
        id: 16,
        logo: "FSSAI.png",
        logoH: '70px',
        logoW: '100px',
        name: "Commissionerate of Food Safety, Govt. of Assam",
    },
    {
        id: 17,
        logo: "APFBC.png",
        logoH: '70px',
        logoW: '70px',
        name: "Assam Project on Forest & Biodiversity Conservation",
    },
    {
        id: 18,
        logo: "MPM.png",
        logoH: '70px',
        logoW: '120px',
        name: "Madhya Pradesh Metro Rail Corporation Ltd.",
    },
    {
        id: 19,
        logo: "CCI.png",
        logoH: '70px',
        logoW: '90px',
        name: "Competition Commission of India",
    },
    {
        id: 20,
        logo: "NRL.png",
        logoH: '70px',
        logoW: '70px',
        name: "Numaligarh Refinery Limited (NRL)",
    },
    {
        id: 21,
        logo: "AUIIP.png",
        logoH: '70px',
        logoW: '80px',
        name: "Assam Urban Infrastructure Investment Program (AUIIP)",
    },
    {
        id: 22,
        logo: "UPSIDA.png",
        logoH: '70px',
        logoW: '140px',
        name: "Uttar Pradesh State Industrial Development Authority (UPSIDA)",
    },
    {
        id: 23,
        logo: "JJM.png",
        logoH: '70px',
        logoW: '70px',
        name: "Jal Jeevan Mission Meghalaya",
    },
    {
        id: 24,
        logo: "EkLakshya.png",
        logoH: '70px',
        logoW: '120px',
        name: "Regional Outreach Bureau, Rajasthan",
    },
    {
        id: 25,
        logo: "SharpSight.png",
        logoH: '70px',
        logoW: '80px',
        name: "Sharp Sight",
    }
];